### PR TITLE
Some fixes

### LINKED ISSUE #3461: Change Hiking text in profile
from
image

to
[ClockSymbol] ca. [hh ,mm]

-> ad a "ca." since  our formula is not the official  formula used by the swiss hiking association

### LINKED ISSUE #3547: local kml is not in selection window when added via drag and drop
reproduce on win10 chrome latest

drag and drop a local kml to viewport

image

expected result

image

work around
move map then the kml appears

### LINKED ISSUE #3575: Swicthing feature doesn't update the tooltip
Found by @AFoletti

Another issue:

draw a line
add a point marker
exit edit mode
select the line --> all is OK
select the point --> info on the point is visualized in the popup, but the line length and option to open profile remains

Expected:
The tooltip is closed then reopens with Point info.

### LINKED ISSUE #3587: Copy link in share does not copy in chrome and win7 and android
Reproduce

win7 chrome and android chrome

from map viewer-> share

A) Ctrl-C
image

or 
B) click on button "Link kopieren"

Result:
Link is not copied anymore in either case A) or B)

### LINKED ISSUE #3588: Create Profile in iframe does not work
Open 
http://www.schoolmaps.ch/2016/04/08/wie-viel-eis-haette-ich-ueber-mein-kopf-gehabt/

Scroll down to 
"Geografie

Konzept der Höhenlinien erklären zum Beispiel Anhand der durch den Gletscher geformten Drumlin Ruetschberg"

select and click
image

Result:
no profile shown

expected result:
profile shown in iframe

### LINKED ISSUE #3593: Layout KML tooltip:
load
http://www.novo-monde.com/rando-lavaux-lac-leman-suisse.php

print icon is in tooltip header overlapping if content is small
image

### PR DESCRIPTION
**Pull request by oterral**
Fix #3575:  [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttp:%2F%2Fwww.respondents.bsv.admin.ch%2Ftemplates%2FKML%2FFinanzhilfe1_fix20161019.kml,KML%7C%7Chttp:%2F%2Fwww.respondents.bsv.admin.ch%2Ftemplates%2FKML%2Fkantonelabel.kml&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=201054.42&Y=632320.43&zoom=2) Click on JU then on NE an see the measure in the tooltip is updated

Fix #3593 : [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?topic=ech&lang=rm&bgLayer=ch.swisstopo.pixelkarte-farbe&X=201054.42&Y=632320.43&zoom=2&layers=KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2FrHD6KrnxQJiJRQ8aNB22bQ) Click on the marker to see the popup resize your window to the tablet size and see the butons are not overlapping the text.

Fix #3588: [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2FJvc6gfsbTzGo4mFhXHKWAA&layers_visibility=false,true&layers_timestamp=18641231,&X=201054.42&Y=632320.43&zoom=2) Click on te measure and see that the "Profile erstellent" link appears in the tooltip then go to share embed page, click on the measure and see that the link doesn't appear in the tooltip.

Fix #3547: [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html) Drag and drop a local KML file and you see tha layer appears in the layermanager.

Fix #3461: [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2FJvc6gfsbTzGo4mFhXHKWAA&layers_visibility=false,true&layers_timestamp=18641231,&X=201054.42&Y=632320.43&zoom=2)  Click on the measure then display the profile.

Fix https://github.com/geoadmin/mf-chsdi3/issues/2278 : [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html?lang=fr&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&X=201805.00&Y=668755.00&dev3d=true&zoom=6&debug&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe,ch.astra.unfaelle-personenschaeden_alle&layers_timestamp=19261231,,&catalogNodes=1179,1180,1186&time=1926) Try to print.

Fix #3587 and #3513 : [Test](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html) Try to copy share link with copy button.

### CODE REVIEW

**Comment by davidoesch** [comment]
#3593 i don't get the print icon on mobile
#3588 i don't get the print profile in embed, keep it as a temporary solution

File: Makefile [hunk 1]
```diff
@@ -682,7 +682,6 @@ $(addprefix .build-artefacts/annotated/, $(SRC_JS_FILES) src/TemplateCacheModule
 ${PYTHON_VENV}:
 	mkdir -p .build-artefacts
 	virtualenv --no-site-packages $@
-	${PIP_CMD} install -U pip
```
Comment (gjn) [inline Makefile]: Why was this done?

**Comment by gjn** [comment]
print no mobile is (AFAIK) always disabled (doesn't make sense...). I think the same is true for embed (to do it in iframe with browser print is non-trivial).

**Comment by davidoesch** [comment]
Correct

File: Makefile (hunk 1 above)
Comment (oterral) [inline Makefile]: It was for upgrading pip. But seems a bad idea because it breaks the teste2e. Don't know why.

Comment (loicgasser) [inline Makefile]: I think it's related to the new ways flake8 is managing extensions since version 3.0.0 (they are to installed per default)
I observed the issue before updating pip.
flake8==2.6.2
solves the issue

Comment (loicgasser) [inline Makefile]: See https://gitlab.com/pycqa/flake8/issues/149

File: src/components/print/PrintDirective.js [hunk 2]
```diff
@@ -245,57 +242,57 @@ goog.require('ga_time_service');
...
-            var source = layer.getSource();
-            var tileGrid = source.getTileGrid();
-            if (!config.background && layer.visible && config.timeEnabled) {
-              layersYears.push(layer.time);
+          var enc = $scope.encoders.layers['Layer'].call(this, layer);
+          var source = layer.getSource();
+          var tileGrid = source.getTileGrid();
+          if (!config.background && layer.visible && config.timeEnabled) {
+            if (!layer.time) {
+              return;
```
Comment (loicgasser) [inline src/components/print/PrintDirective.js]: YUP

File: src/components/print/PrintDirective.js [hunk 3]
```diff
@@ -535,10 +532,30 @@ goog.require('ga_time_service');
 
       // Transform layers to literal
       layers.forEach(function(layer) {
-        if (layer.visible && (!layer.timeEnabled ||
-            angular.isDefined(layer.time))) {
+        if (!layer.visible || layer.opacity == 0) {
```
Comment (loicgasser) [inline src/components/print/PrintDirective.js]: ``|| layer.preview`` ? to be extra sure

**Comment by loicgasser** [comment]
LGTM

File: Makefile (hunk 1 above)
Comment (oterral) [inline Makefile]: Ok I change.

File: src/components/print/PrintDirective.js (hunk 3 above)
Comment (oterral) [inline src/components/print/PrintDirective.js]: technically it's impossible a preview layer is displayed when you push print button.

**Comment by oterral** [comment]
please a last review @gjn or @loicgasser I've fixed the copy link button in share. It works with FF too.

**Comment by gjn** [comment]
LGTM. Thanks alot.
