### PR TITLE
Added fixed WMS - Maps4BW : will fix #3855

### LINKED ISSUE #3855: Warning message external data on switch 2d ->3d if wgs84 is not supported
Open WMTS https://s.geo.admin.ch/73d1a50ff4
-> wgs84 not supported therefore data not shown in 3d.

expected result: show warning message
"One ore more external sources does not support WGS84, data will not be displayed in 3d"

### PR DESCRIPTION
**Pull request by davidoesch**
Got feedback from BW  : new official https://owsproxy.lgl-bw.de/owsproxy/ows/WMS_Maps4BW?request=GetCapabilities&service=WMS&Version=1.3.0

### CODE REVIEW

File: src/js/ImportController.js [hunk 1]
```diff
@@ -159,6 +159,7 @@ goog.require('ngeo.fileService');
         'http://osm.omniscale.net/proxy/service',
         'https://ows.terrestris.de/osm/service',
         'https://ows.terrestris.de/osm-gray/service',
+        'https://owsproxy.lgl-bw.de/owsproxy/ows/WMS_Maps4BW?request=GetCapabilities&service=WMS&Version=1.3.0'
```
Comment (loicgasser) [inline src/js/ImportController.js]: @davidoesch your forgot the comma ;)

**Comment by davidoesch** [comment]
thanks ( that is what review is 4 ;-)
