### PR TITLE
Fix #2531: Forbid the send of 2 identical requests

### LINKED ISSUE #2531: IE9 browserstack tests fail since today
Git bisect revealed that this commit:

https://github.com/geoadmin/mf-geoadmin3/commit/975cdc38f5d2b2d6a15cf3849e846c00748b1aa9

makes the IE9 browserstack tests fail. The test only checks for page loading by checking for existence of the first catalog element -> https://github.com/geoadmin/mf-geoadmin3/blob/master/test/selenium/start_test.js#L14

All other browsers in browserstack are doing good. Also, when opening by hand on IE9, I can see the catalog well.

@oterral any idea?

### PR DESCRIPTION
**Pull request by oterral**

### CODE REVIEW

**Comment by oterral** [comment]
Bad PR. Breaks https://github.com/geoadmin/mf-geoadmin3/issues/2512

File: src/components/catalogtree/CatalogtreeDirective.js [hunk 1]
```diff
@@ -116,12 +116,18 @@ goog.require('ga_translation_service');
...
+                // We forbid the send of 2 identical requests (needed for IE9);
+                // See http://github.com/geoadmin/mf-geoadmin3/issues/2531/
+                if (lastLangUsed == lang) {
+                  return;
+                }
               }
-              lastUrlUsed = url;
               if (canceller) {
-                canceller.resolve();
+               canceller.resolve();
```
Comment (gjn) [inline src/components/catalogtree/CatalogtreeDirective.js]: ident

**Comment by gjn** [comment]
woaaa. great.

fix ident, then merge. and thanks alot!
