### PR TITLE
[MVT] Fixes

### LINKED ISSUE #4567: [MVT] Can t load KML files
Steps to reproduce:
 - Open this [link](https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7e340acd52)

----->> A kml should appear

Expected:
  - the kml is displayed

There is an access deny error  on the KML files from public .
@procrastinatio @loicgasser  do you have an idea why ?

### PR DESCRIPTION
**Pull request by oterral**
fix #4567 

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/teo_fixes/index.html)</jenkins>

### CODE REVIEW

File: src/components/map/LayersService.js [hunk 1]
```diff
@@ -750,19 +750,24 @@ goog.require('ga_urlutils_service');
               var subLayerConf = layers[subLayersIds[i]];
               if (styleUrl && subLayerConf) {
                 layers[subLayersIds[i]].styleUrl = config.styleUrl;
-
-                gaGlStyle.get(styleUrl).then((glStyle) => {
-                  gaMapUtils.applyGlStyleToOlLayer(olLayer, glStyle);
-                });
```
Comment (loicgasser) [inline src/components/map/LayersService.js]: this explains the extra calls to olms
