### PR TITLE
Manage render errors

### LINKED ISSUE #2890: 3D mode:  does not load in IE11 on mobile device (surface)
OS: Windows 8
BROWSER: IE11
LINK: https://mf-geoadmin3.int.bgdi.ch/3dalpha/
STEPS TO REPRODUCE: click on 3D button
RESULT: background becomes white and then application freezes.

### PR DESCRIPTION
**Pull request by oterral**
Fix  #2890

### CODE REVIEW

File: src/js/MainController.js [hunk 1]
```diff
@@ -95,6 +95,15 @@ goog.require('ga_topic_service');
         startWith3D = true;
       }
 
+      var onRenderError = function(scene, error) {
+        $scope.globals.is3dActive = undefined;
+        alert($translate.instant('3d_render_error'));
+        $window.console.error(error.stack);
```
Comment (gjn) [inline src/js/MainController.js]: We want to keep that?

File: src/lib/Cesium/Cesium.js [hunk 2]
```diff
@@ -139438,17 +139438,17 @@ define('Scene/QuadtreeTile',[
...
-                result[index++] = new QuadtreeTile({
+        for (var y = topRight.y; y <= bottomLeft.y; y++) {
+            for (var x = bottomLeft.x; x <= topRight.x; x++) {
+                result.push(new QuadtreeTile({
                     tilingScheme : tilingScheme,
                     x : x,
                     y : y,
                     level : level
-                });
+                }));
```
Comment (gjn) [inline src/lib/Cesium/Cesium.js]: These changes here seem to be unrelated...

File: src/locales/empty.json [hunk 3]
```diff
@@ -355,5 +355,6 @@
   "help_search_data": "",
   "query_operator": "",
   "no_more_information": "",
-  "3d_ie11_alert": ""
+  "3d_ie11_alert": "",
+  "3d_render_error": ""
```
Comment (gjn) [inline src/locales/empty.json]: Translations needed before merge

File: src/lib/Cesium/Cesium.js (hunk 2 above)
Comment (oterral) [inline src/lib/Cesium/Cesium.js]: Totally I miss my checkout of this file

File: src/js/MainController.js (hunk 1 above)
Comment (oterral) [inline src/js/MainController.js]: I'm in favor to keep this because it's a fatal error of cesium (we already use it when the inialisation failed). It's easier to see why the 3d doesn't work, and also because the native webgl msg is not so clear.

Comment (gjn) [inline src/js/MainController.js]: ok

**Comment by oterral** [comment]
@davidoesch what message do you want to display?

**Comment by davidoesch** [comment]
the one we already have in place for IE11

**Comment by gjn** [comment]
This is different. The one before is saying to switch browser because of performance.

This is saying 3D does not work and might also happen on other platforms/browsers.

**Comment by davidoesch** [comment]
did you find anything at CESIUM? How do they handle this? I did not find a
text

On Wed, Nov 18, 2015 at 11:44 AM, Gilbert Jeiziner <notifications@github.com

**Comment by oterral** [comment]
Cesium displays only the native error message and the stacktrace

**Comment by davidoesch** [comment]
did update all msgid "3d_render_error"

@pauloamado the https://support.google.com/maps/answer/3096703?hl=en we will copy paste for the 3d help

**Comment by oterral** [comment]
@gjn translation updated

**Comment by gjn** [comment]
Thanks alot.
